# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_color', models.CharField(max_length=200)),
                ('white_color', models.CharField(blank=True, max_length=200)),
                ('marks', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='N/N', max_length=200)),
                ('base_formula', models.CharField(max_length=200)),
                ('silver', models.CharField(choices=[('Zz', 'Zz'), ('ZZ', 'ZZ'), ('zz', 'zz'), ('N/N', 'N/N')], default='N/N', max_length=10)),
                ('cream', models.CharField(choices=[('CcrCcr', 'CcrCcr'), ('Ccr/ccr', 'Ccr/ccr'), ('ccr/ccr', 'ccr/ccr'), ('N/N', 'N/N')], default='N/N', max_length=10)),
                ('dun', models.CharField(choices=[('Dd', 'Dd'), ('DD', 'DD'), ('dd', 'dd'), ('N/N', 'N/N')], default='N/N', max_length=10)),
                ('champagne', models.CharField(choices=[('Chch', 'Chch'), ('CHCH', 'CHCH'), ('chch', 'chch'), ('N/N', 'N/N')], default='N/N', max_length=10)),
                ('disease', models.CharField(blank=True, max_length=200)),
                ('color', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='baback.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('Ж', 'Жеребец'), ('К', 'Кобыла'), ('М', 'Мерин')], max_length=1)),
                ('birth_date', models.IntegerField()),
                ('death_date', models.IntegerField(blank=True, null=True)),
                ('breed', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='images/base.jpg', upload_to='images')),
                ('genes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='baback.Genotype')),
                ('horse_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baback.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=200)),
                ('lab_country', models.CharField(max_length=200)),
                ('lab_method', models.CharField(max_length=200)),
                ('lab_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('farm', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(default='Nope@heckno.ru', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='horse',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='baback.Owner'),
        ),
        migrations.AddField(
            model_name='genotype',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='baback.Lab'),
        ),
    ]
